suppressPackageStartupMessages({library(ggplot2);library(cowplot)})
args<-commandArgs(TRUE);stopifnot(length(args)==1);O<-normalizePath(args[1],winslash='/')
dir.create(file.path(O,'supplementary'),showWarnings=FALSE)
r<-read.delim(file.path(O,'source_data/conditional_results.tsv'),check.names=FALSE)
d<-read.delim(file.path(O,'source_data/conditional_patient_diagnostics.tsv'),check.names=FALSE)
family<-c('Immature epithelial','Absorptive epithelial','Mature absorptive epithelial','Secretory epithelial')
mods<-c('ICI_COLITIS_EPITHELIAL_UP_NON_IFN','ICI_COLITIS_EPITHELIAL_LOSS_STRICT')
lab<-setNames(c('Non-IFN residual','Disease-depleted'),mods)
r<-r[r$dataset=='GSE206300',];d<-d[d$dataset=='GSE206300',]
r$celltype<-factor(r$celltype,levels=rev(family));d$celltype<-factor(d$celltype,levels=family)
theme_set(theme_classic(base_size=9)+theme(text=element_text(colour='#243440'),axis.text=element_text(colour='#243440'),plot.title=element_text(size=11,face='bold'),plot.subtitle=element_text(size=8),plot.margin=margin(8,8,8,8)))
savep<-function(p,id,h){b<-file.path(O,'supplementary',id);ggsave(paste0(b,'.pdf'),p,width=7.2,height=h,device=cairo_pdf,bg='white');ggsave(paste0(b,'.tiff'),p,width=7.2,height=h,dpi=600,device=grDevices::tiff,compression='lzw',bg='white');ggsave(paste0(b,'_preview.png'),p,width=7.2,height=h,dpi=200,bg='white')}
pan<-lapply(mods,function(m){z<-r[r$module==m,];ggplot(z,aes(y=celltype,x=adjusted_beta))+geom_vline(xintercept=0,colour='#B7BDC1',linetype=2)+geom_segment(aes(x=ci_low,xend=ci_high,yend=celltype),linewidth=.6,colour='#247E91')+geom_point(size=2.5,colour='#247E91')+geom_point(aes(x=unadjusted_beta),shape=1,size=2,colour='#777777')+geom_text(aes(x=.091,label=sprintf('q=%.3f',fdr)),hjust=1,size=2.7)+coord_cartesian(xlim=c(-.10,.095))+labs(title=lab[[m]],x='Case minus control rank-score difference',y=NULL)})
head<-ggdraw()+draw_label('Does the epithelial programme add information beyond IFN?',x=.02,hjust=0,fontface='bold',size=12)
foot<-ggdraw()+draw_label('Independent GSE206300: 8 irColitis patients and 5 PD-1-treated controls in each family.\nFilled: IFN-adjusted coefficient and pointwise 95% HC3 t interval; open: unadjusted coefficient.\nBH correction covers all 8 tests. Limited IFN overlap makes conditional estimates model-dependent.\nFour epithelial families come from the same cohort; no causal independence is inferred.',x=.02,hjust=0,size=8)
savep(plot_grid(head,plot_grid(plotlist=pan,ncol=1,labels=c('a','b')),foot,ncol=1,rel_heights=c(.45,5,.9)),'Supplementary_Figure_13A_IFN_conditional_effects',6.35)
plots<-lapply(mods,function(m){z<-d[d$module==m,];ggplot(z,aes(IFN_score,oriented_score,colour=condition))+geom_point(size=2.1,alpha=.95)+facet_wrap(~celltype,ncol=2,scales='free')+scale_colour_manual(values=c('On ICI therapy'='#327BA3','irColitis'='#C15449'),labels=c('ICI-treated control','ICI colitis'),name=NULL)+labs(title=lab[[m]],x='Frozen IFN mean expression rank',y='Disease-oriented programme rank')+theme(legend.position='bottom',strip.background=element_blank(),strip.text=element_text(size=8,face='bold'))})
foot2<-ggdraw()+draw_label('Each point is one patient and epithelial family; the two outcomes use the same patients.\nAll observed values are shown. Axes vary by family to expose overlap and leverage.\nNo regression band, donor duplication or independent-cohort claim is added.',x=.02,hjust=0,size=8)
savep(plot_grid(plot_grid(plotlist=plots,ncol=1,labels=c('c','d')),foot2,ncol=1,rel_heights=c(8,.7)),'Supplementary_Figure_13B_IFN_patient_overlap',8.7)
write.table(data.frame(figure=c('Supplementary_Figure_13A_IFN_conditional_effects','Supplementary_Figure_13B_IFN_patient_overlap'),width_in=7.2,height_in=c(6.35,8.7),tiff_dpi=600),file.path(O,'review/conditional_figure_dimensions.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
write.table(data.frame(panel=c('SF13a-b','SF13c-d'),source=c('source_data/conditional_results.tsv','source_data/conditional_patient_diagnostics.tsv'),key=c('dataset|celltype|module','dataset|celltype|module|patient_id'),unit=c('patient; conditional coefficient','patient; observed score')),file.path(O,'review/conditional_panel_source_map.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
cat('CONDITIONAL_FIGURES_PASS\n')
