suppressPackageStartupMessages({library(ggplot2);library(cowplot);library(dplyr);library(tidyr)})
args<-commandArgs(TRUE);stopifnot(length(args)==1);O<-normalizePath(args[1],winslash='/');E<-file.path(O,'visual_input_snapshot/organoid_donor_extension')
source(file.path(O,'presentation_code/csv_io.R'))
z<-jsonlite::fromJSON(file.path(E,'review/analysis_complete.json'));stopifnot(z$status=='PASS');R<-Sys.getenv('ICI_RECORDED_ORGANOID_RESULTS',unset='');if(!nzchar(R)||!dir.exists(R))stop('BLOCKED_INPUT: ICI_RECORDED_ORGANOID_RESULTS')
plan<-jsonlite::fromJSON(file.path(E,'review/analysis_plan_locked.json'))
g<-read.csv(file.path(R,'module_GSEA.csv'));s<-read.csv(file.path(R,'donor_module_scores.csv'));core<-read.csv(file.path(E,'source_data/frozen_core_donor_gene_effects.csv'))
conds<-c('TNFSF12',plan$secondary_ligands,'No_Cytomix');cts<-plan$celltypes
mods<-c('CURATED_IFN_VISIBILITY','ICI_COLITIS_EPITHELIAL_UP_STRICT','ICI_COLITIS_EPITHELIAL_UP_NON_IFN','ICI_COLITIS_EPITHELIAL_LOSS_STRICT');mlab<-setNames(c('IFN visibility','Disease-up','IFN-gene-excluded residual','Disease-depleted'),mods)
clab<-setNames(c('Stem','TA','Colonocyte','Goblet'),cts);colors<-setNames(c('#2C79A6','#C14A43','#795AA6','#C59633'),cts)
source(file.path(O,'presentation_code/theme_final.R'))
dimensions<-list()
savep<-function(p,id,h){
 ids<-c(Supplementary_Figure_15A_complete_donor_GSEA='S5A',Supplementary_Figure_15B_complete_donor_points='S5B',Supplementary_Figure_16_complete_core_donor_models='S4B')
 if(!id%in%names(ids))return(invisible(NULL))
 b<-file.path(O,'supplement/plates',ids[[id]])
 ggsave(paste0(b,'.pdf'),p,width=180,height=h*25.4,units='mm',device=cairo_pdf,bg='white')
 ggsave(paste0(b,'.png'),p,width=180,height=h*25.4,units='mm',dpi=300,bg='white')
 dimensions[[length(dimensions)+1]]<<-data.frame(figure=ids[[id]],width_mm=180,height_mm=h*25.4)
 message('Supplement plate ',ids[[id]])
}
lim<-max(abs(g$NES),na.rm=TRUE)
pan<-lapply(mods,function(m){d<-g[g$module==m,];d$ligand<-factor(d$ligand,levels=rev(conds));d$celltype<-factor(d$celltype,levels=cts);d$label<-ifelse(is.na(d$NES),'NE',paste0(sprintf('%.2f',d$NES),ifelse(d$FDR_predeclared_family<.05,'*','')));ggplot(d,aes(celltype,ligand,fill=NES))+geom_tile(colour='white')+geom_text(aes(label=label),size=2.8)+geom_hline(yintercept=c(1.5,7.5),colour='#283E4D',linewidth=.45)+scale_x_discrete(labels=clab)+scale_y_discrete(labels=function(x)ifelse(x=='No_Cytomix','No cytomix',x))+scale_fill_gradient2(low='#356B91',mid='white',high='#B84B46',limits=c(-lim,lim),na.value='#D4D9DD',name='NES')+labs(title=mlab[[m]],x=NULL,y=NULL)+theme(legend.position='bottom',axis.text.x=element_text(angle=30,hjust=1))})
foot<-ggdraw()+draw_label('All original directional nominees and the assay reference are shown. Each cell is a model estimate.\n* FDR < 0.05 within the declared family: TNFSF12 16 tests; other nominees 96; reference 16.\nGrey NE cells are not estimable under the fixed donor/cell requirements.\nThe nominations arose from the same experiment; this is a targeted sensitivity analysis.',x=.02,hjust=0,size=8)
savep(plot_grid(plot_grid(plotlist=pan,ncol=2,labels=letters[1:4]),foot,ncol=1,rel_heights=c(7.2,.9)),'Supplementary_Figure_15A_complete_donor_GSEA',8.1)
delta<-s%>%select(ligand,celltype,module,donor,treatment,raw_mean_rank)%>%pivot_wider(names_from=treatment,values_from=raw_mean_rank)%>%mutate(change=Treatment-Control)
donors<-sort(unique(delta$donor));offset_ct<-setNames(seq(-.30,.30,length.out=length(cts)),cts);offset_donor<-setNames(seq(-.045,.045,length.out=length(donors)),donors)
delta$display_y<-match(delta$ligand,rev(conds))+offset_ct[delta$celltype]+offset_donor[delta$donor]
pan2<-lapply(mods,function(m){d<-delta[delta$module==m,];ggplot(d,aes(change,display_y,colour=celltype,shape=donor))+geom_vline(xintercept=0,colour='#A5ADB2',linetype=2)+geom_hline(yintercept=c(1.5,7.5),colour='#C3C9CD',linewidth=.35)+geom_point(size=1.65)+scale_y_continuous(breaks=seq_along(conds),labels=gsub('No_Cytomix','No cytomix',rev(conds)),limits=c(.45,8.55))+scale_colour_manual(values=colors,labels=clab)+labs(title=mlab[[m]],x='Treatment minus control raw rank',y=NULL,colour='Family',shape='Donor')+theme(legend.position='bottom',legend.text=element_text(size=7))+guides(colour=guide_legend(nrow=2),shape=guide_legend(nrow=1))})
foot2<-ggdraw()+draw_label('Each point is an observed paired donor change; horizontal coordinates are unaltered data values.\nSmall vertical offsets separate families and donors. Positive means increased relative expression.\nOnly contrasts with three matched donors are shown here; all exclusions remain in the source tables.\nNo confidence bands or donor-like points are inferred from gene-set results.',x=.02,hjust=0,size=8)
shared_legend<-get_legend(pan2[[1]]+theme(legend.box='horizontal',legend.position='bottom')+guides(colour=guide_legend(nrow=1,order=1),shape=guide_legend(nrow=1,order=2)))
pan2<-lapply(pan2,function(p)p+theme(legend.position='none'))
savep(plot_grid(plot_grid(plotlist=pan2,ncol=2,labels=letters[5:8]),shared_legend,foot2,ncol=1,rel_heights=c(7.65,.45,.9)),'Supplementary_Figure_15B_complete_donor_points',9)
write.table(delta,file.path(O,'source_data/display/S5B_all_donor_plot_coordinates.csv'),sep=',',row.names=FALSE,quote=TRUE)
genes<-sort(unique(core$gene));half<-ceiling(length(genes)/2);lim2<-max(abs(core$log2FoldChange),na.rm=TRUE)
cp<-lapply(split(genes,ceiling(seq_along(genes)/half)),function(gs){d<-core[core$gene%in%gs,];d$gene<-factor(d$gene,levels=rev(gs));d$celltype<-factor(d$celltype,levels=cts);d$mark<-ifelse(is.na(d$log2FoldChange),'NE',ifelse(d$padj<.05,'*',''));ggplot(d,aes(celltype,gene,fill=log2FoldChange))+geom_tile(colour='white',linewidth=.15)+geom_text(aes(label=mark),size=2.7)+scale_x_discrete(labels=clab)+scale_fill_gradient2(low='#356B91',mid='white',high='#B84B46',limits=c(-lim2,lim2),na.value='#D4D9DD',name='log2FC')+labs(x=NULL,y=NULL)+theme(axis.text.y=element_text(size=8),axis.text.x=element_text(angle=30,hjust=1),legend.position='bottom')})
head<-ggdraw()+draw_label('Every frozen reciprocity-core gene in the paired donor models',x=.02,hjust=0,fontface='bold',size=12)
foot3<-ggdraw()+draw_label('Gene membership remains the original positive leading edge; no reselection by new effect or FDR.\n* Gene-level FDR < 0.05 within each donor model. NE is distinct from a non-significant estimate.\nThese models use the same perturbation experiment; external disease effects remain in Supplementary Fig. S4a-b.',x=.02,hjust=0,size=8)
savep(plot_grid(head,plot_grid(plotlist=cp,ncol=2,labels=c('c','d')),foot3,ncol=1,rel_heights=c(.4,7.9,.8)),'Supplementary_Figure_16_complete_core_donor_models',9.1)
write.table(do.call(rbind,dimensions),file.path(O,'review/organoid_supplement_figure_dimensions.csv'),sep=',',row.names=FALSE,quote=TRUE)
write.table(data.frame(panel=c('SF15a-d','SF15e-h','SF16a-b'),source=c(file.path(R,'module_GSEA.csv'),file.path(O,'source_data/display/S5B_all_donor_plot_coordinates.csv'),file.path(E,'source_data/frozen_core_donor_gene_effects.csv')),key=c('ligand|celltype|module','ligand|celltype|module|donor','ligand|celltype|gene'),unit=c('gene-set model estimate','donor','gene within donor model')),file.path(O,'review/organoid_supplement_panel_map.csv'),sep=',',row.names=FALSE,quote=TRUE)
cat('ORGANOID_SUPPLEMENT_FIGURES_PASS\n')

